/* Generated by hooks/lang_toggle.py -- do not edit by hand. */
(function () {
  var EN_PAGES = ["/", "/blog/", "/contact/", "/member/", "/publications/", "/recruitment/", "/research/"];

  function normalise(p) {
    if (!p.endsWith("/")) p += "/";
    return p;
  }

  function counterparts(path) {
    path = normalise(path);
    var isEn = path === "/en/" || path.startsWith("/en/");
    var bare = isEn ? path.slice(3) : path;          // "/en/research/" -> "/research/"
    if (bare === "") bare = "/";
    var hasEn = EN_PAGES.indexOf(bare) !== -1;
    return {
      ja: bare,
      // fall back to the English home page when this page has no English version
      en: hasEn ? "/en" + (bare === "/" ? "/" : bare) : "/en/"
    };
  }

  function apply() {
    var targets = counterparts(window.location.pathname);
    document.querySelectorAll("a[hreflang]").forEach(function (a) {
      var lang = a.getAttribute("hreflang");
      if (lang === "ja") a.setAttribute("href", targets.ja);
      else if (lang === "en") a.setAttribute("href", targets.en);
    });
  }

  if (document.readyState !== "loading") apply();
  else document.addEventListener("DOMContentLoaded", apply);

  // Material loads pages via XHR when instant navigation is on.
  if (window.document$ && typeof window.document$.subscribe === "function") {
    window.document$.subscribe(apply);
  }
})();
