/* Generated by hooks/lang_toggle.py -- do not edit by hand. */
(function () {
  var EN_PAGES = ["/", "/blog/", "/contact/", "/member/", "/publications/", "/recruitment/", "/research/"];
  var STORE = "nphys.lang";

  function normalise(p) {
    if (!p.endsWith("/")) p += "/";
    return p;
  }

  function counterparts(path) {
    path = normalise(path);
    var isEn = path === "/en/" || path.startsWith("/en/");
    var bare = isEn ? path.slice(3) : path;          // "/en/research/" -> "/research/"
    if (bare === "") bare = "/";
    var hasEn = EN_PAGES.indexOf(bare) !== -1;
    return {
      ja: bare,
      // fall back to the English home page when this page has no English version
      en: hasEn ? "/en" + (bare === "/" ? "/" : bare) : "/en/"
    };
  }

  function stored() {
    try { return localStorage.getItem(STORE); } catch (e) { return null; }
  }

  /* Send a first-time visitor to the version matching their browser language.
     Deliberately narrow:
       - only from the site root, so a shared deep link is never hijacked
       - only when the visitor has not already chosen a language themselves
       - location.replace, so it does not trap the back button */
  function autoLanguage() {
    var path = window.location.pathname;
    if (path !== "/" && path !== "/index.html") return;
    if (stored()) return;
    var langs = navigator.languages || [navigator.language || ""];
    var wantsJa = Array.prototype.some.call(langs, function (l) {
      // plain comparison rather than a regex: backslash escapes in this template
      // are evaluated twice and silently corrupt the pattern
      l = String(l).toLowerCase();
      return l === "ja" || l.indexOf("ja-") === 0;
    });
    if (!wantsJa) window.location.replace("/en/");
  }

  /* Using the switch counts as choosing, and is remembered from then on. */
  function rememberChoice() {
    document.querySelectorAll("a[hreflang]").forEach(function (a) {
      a.addEventListener("click", function () {
        try { localStorage.setItem(STORE, a.getAttribute("hreflang")); } catch (e) {}
      });
    });
  }

  function apply() {
    var targets = counterparts(window.location.pathname);
    document.querySelectorAll("a[hreflang]").forEach(function (a) {
      var lang = a.getAttribute("hreflang");
      if (lang === "ja") a.setAttribute("href", targets.ja);
      else if (lang === "en") a.setAttribute("href", targets.en);
    });
    rememberChoice();
  }

  autoLanguage();

  if (document.readyState !== "loading") apply();
  else document.addEventListener("DOMContentLoaded", apply);

  // Material loads pages via XHR when instant navigation is on.
  if (window.document$ && typeof window.document$.subscribe === "function") {
    window.document$.subscribe(apply);
  }
})();
